version: "3.7"
services:
  webapp:
    build: .
    ports:
      - "3000:3000"
    depends_on:
      - mongodb
    env_file: .env
    environment:
      - BOILERPLATECONFIG_server_db_connectionString=mongodb://mongodb:27017
  mongodb:
    # TODO: Specify a Mongo version
    image: mongo:latest
    expose:
      - "27017"

